In [8]:
import pandas as pd
from scipy.stats import f_oneway

In [9]:
# Create a DataFrame with your data
data = pd.read_csv("../data/profiles.csv")

df = pd.DataFrame(data)
df.head(5)

,Nom et Prénom,ASS - Unevercity,Spciality,H indice global,Citations global,H indie_cI10 global,H indice depuis 2018,Citations depuis 2018,H indice_I10 depuis 2018,Article Count,faculty
0,salah er-raki,"ProcEDE- FST de Marrakech,Université Cadi Ayyad","physique, irrigation, Agricultural Sciences, r...",37,5231,69,34,3308,63,20,FSTG
1,Abdelkader Outzourhit,Université Cadi Ayyad,"Energies renouvelables, PV, Stockage",29,3973,105,22,1899,66,20,Other
2,Jamal Ezzahar,"MISCOM, ENSA Safi,Université Cadi Ayyad Marrakech","Land-atmosphere interactions, Soil Moisture, R...",28,3703,46,26,2399,41,20,ENSA
3,ouazzani naaila,"professeur à l'université Cadi Ayyad, Marrakech",Wastewater treatment and reuse,31,3549,72,26,2502,60,20,NaN
4,Saïd Khabba,Professeur de l'Université Cadi Ayyad,"Ressources en eau, Besoin en eau des cultures,...",32,3474,65,28,2490,53,20,NaN

In [13]:
# Define groups for the ANOVA test
groups = df["faculty"].unique()

# Check for missing values
print("Missing values:")
print(df.isnull().sum())

# Drop rows with missing values (you may choose a different approach)
df_clean = df.dropna()

# Perform ANOVA for H indice global
h_index_anova = f_oneway(*[df_clean[df_clean["faculty"] == group]["H indice global"] for group in groups])

# Perform ANOVA for Citations global
citations_anova = f_oneway(*[df_clean[df_clean["faculty"] == group]["Citations global"] for group in groups])

# Print ANOVA results
print("\nANOVA for H indice global:")
print(h_index_anova)

print("\nANOVA for Citations global:")
print(citations_anova)

Missing values:
Nom et Prénom                0
ASS - Unevercity             0
Spciality                    1
H indice global              0
Citations global             0
H indie_cI10 global          0
H indice depuis 2018         0
Citations depuis 2018        0
H indice_I10 depuis 2018     0
Article Count                0
faculty                     14
dtype: int64

ANOVA for H indice global:
F_onewayResult(statistic=nan, pvalue=nan)

ANOVA for Citations global:
F_onewayResult(statistic=nan, pvalue=nan)

c:\Python311\Lib\site-packages\scipy\stats\_stats_py.py:3861: DegenerateDataWarning: at least one input has length 0
  warnings.warn(stats.DegenerateDataWarning('at least one input '